### ISSUE TITLE
The released binary doesn't run on the newest version of java

### ISSUE THREAD

**Issue by h0dgep0dge** [ConnorDY/OSRS-Environment-Exporter#59]
This is maybe more of a feature request than a bug report, but java binary provided with this project doesn't run with the newest version of java 8, and to get it running I needed to download an archived version of java 11. It would be nice and more user-friendly to release a binary that works with java 8

**Comment by ScoreUnder** [comment]
Java 8 (2014) is older than Java 11 (late 2018). I have been testing this project mainly on Java 18 (early 2022). Java 8 is still receiving bugfixes and security updates, and will continue to do so for the next 8 years, but it is a relatively old version of Java nowadays to the point that [even Minecraft has stopped supporting it](https://minecraft.fandom.com/wiki/Tutorials/Update_Java#Why_update?).

Microsoft provides some newer Java versions on their own website: https://docs.microsoft.com/en-gb/java/openjdk/download

Currently blocking a version 8 downgrade we have:
* Some dependencies are not built for version 8 (LAF classes)
* Some dependencies are built for version 8, but not actually working on version 8 (3D library at least, maybe others?)
* All devs would need to use jdk 8 to test. Some very subtle things, like calling `aByteBuffer.position(Int)` instead of `(aByteBuffer as Buffer).position(Int)` cause incompatibility because a method with an identical name but more specific signature has appeared in version 9

**Comment by h0dgep0dge** [comment]
I guess all I know is that I tried to run jar with the version of java i have, the newest version the updater would give me, and it didn't work. i was able to get it to work, but i suppose many people won't be able to. someone else posted about this problem on reddit, and Connor_DY told them to make a bug report, so that's what i've done. i suppose all we can do is lament the absolute state of the java ecosystem, thanks for the reply
